#!/usr/bin/env bash

# Simple git alias to allow cloning of openstack repos by name.

repos=('https://github.com/openstack/' 'https://github.com/openstack-dev/')

if [ $# != 1 ]; then
    echo "Usage: osclone <project>"
    exit 1
fi

for repo in ${repos[@]}; do
    git ls-remote "${repo}${1}" &>-
    if [ $? -eq 0 ]; then
        git clone ${repo}${1}
        exit 0
    fi
done

echo "Unable to find '${1}'."
exit 1
